### ISSUE TITLE
can not compose

### ISSUE THREAD

**Issue by bl4z3it** [sedlund/piaqbittorrent#4]
when i try to compose it, i get this error (docker-compose up -d):

Building vpn
Step 1/16 : FROM --platform=$BUILDPLATFORM alpine:3 AS builder
ERROR: Service 'vpn' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument

**Comment by bl4z3it** [comment]
tried it for 3rd time, now it works lol

**Comment by sedlund** [comment]
Hmm.  Shouldn't need to be built.  I guess a `docker-compose pull` should be done before `up` if you don't have the images locally yet.

If someone is trying to build it by hand that --platform=$BUILDPLATFORM is an option of docker buildx.  If you aren't setup to build with buildx, you can remove the --platform=... option and just use docker build
