### ISSUE TITLE
qbt_qb_1 container keeps restarting

### ISSUE THREAD

**Issue by bl4z3it** [sedlund/piaqbittorrent#5]
running on a raspberry pi 3b+with a new raspbian installation (
cd ~/
mkdir test
git clone https://github.com/sedlund/piaqbittorrent.git .
//editing the .yaml and .env files like in the instruction
docker-compose pull
docker-compose up -d
)
i can access the webinterface for like 5 seconds, then after reloading i get logged out, the sites is not accessible for ~2 seconds and then it is starting again

docker ps output:
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS                             PORTS                              NAMES
0f66ef22201d        sedlund/qbittorrent   "/qb/start.sh"      5 minutes ago       Restarting (1) 2 seconds ago                                          qbt_qb_1
5109739beb54        sedlund/piavpn        "/vpn/start.sh"     5 minutes ago       Up 51 seconds (health: starting)   0.0.0.0:8080->8080/tcp, 9047/tcp   qbt_vpn_1

can you help me?

**Comment by sedlund** [comment]
attach output of `docker-compose logs`

there may be plain text passwords or other things you may not want to share, so look first - change as necessary.

**Comment by bl4z3it** [comment]
i use another setup now so this is not a problem anymore, thank you anyways
